[project]
name = "cviers-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.13.0",
    "kafka-python>=2.3.0",
    "pre-commit>=4.6.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "deepdiff>=9.0.0",
    "pytest>=9.0.3",
]

[tool.uv.workspace]
members = [
    "civers_common",
    "civers_change_detection",
    "civers_archive_generator",
    "civers_metadata_extractor",
    "civers_orchestrator",
    "civers_archive_web_interface",
]
