app:
  metadata:
    web_interface_url: "${WEB_INTERFACE_URL:-http://web-interface:8000}"

transport:
  kafka:
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
    consumer:
      auto_offset_reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:-earliest}
    producer:
      acks: ${KAFKA_PRODUCER_ACKS:-all}
      retries: ${KAFKA_PRODUCER_RETRIES:-3}
